### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.0

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by goanpeca** [comment]
@jakirkham do you know why is appveyor not being triggered?

**Comment by jakirkham** [comment]
Probably because of this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/314 ).

**Comment by goanpeca** [comment]
So should I merge and restart a new build from within appveyor? (I dont expect the win build to fail as it is just an update for conda-smithy)

**Comment by jakirkham** [comment]
Up to you. Just would note we will have the same problem with AppVeyor on `master`. So you may need to restart it later when the rate limit is reset.

**Comment by goanpeca** [comment]
Ok, would closing and reopening this PR trigger appveyor once the rate limit is reset?

**Comment by jakirkham** [comment]
Yep that would work. GitHub resets the rate limit every 1hr period. Though we are likely somewhere in the middle of that period when it expires. So it is probably less.

**Comment by jakirkham** [comment]
Asking AppVeyor about getting some info about the time left when this happens so that I can give you and others a better idea of when things will be back online.

**Pull request merged**
